name: Platform/ufmt
on:
  pull_request:
    branches:
    - main
jobs:
  ufmt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ruff-api
        run: pip install ruff-api==0.1.0
      - name: Check formatting
        uses: omnilib/ufmt@action-v1
        with:
          path: web-auto sam3-api ops-api sapiens-api locate-anything-api scripts tests
          python-version: "3.12"
          black-version: "24.2.0"
          usort-version: "1.0.2"
